# Declaring features:
"""
Here are lists containing features for doing SVM and Decision tree algorithm,
each one is a different iteration. The list contains two elements, the first
of wich is the list containing feature_name in the csv file, while the second
of which is the list of its corresponding translation in Chinese for reading
enhancement. Examples are:
key_1 = [[feature_names], [corresponding_translations]]
"""
all_keys = [['temp', 'time', 'slowCool', 'pH', 'leak', 'numberInorg', 'numberOrg', 'numberOxlike',
             'numberComponents', 'orgavgpolMax', 'orgrefractivityMax', 'orgmaximalprojectionareaMax',
             'orgmaximalprojectionradiusMax', 'orgmaximalprojectionsizeMax', 'orgminimalprojectionareaMax',
             'orgminimalprojectionradiusMax', 'orgminimalprojectionsizeMax', 'orgavgpol_pHdependentMax',
             'orgmolpolMax', 'orgvanderwaalsMax', 'orgASAMax', 'orgASA+Max', 'orgASA-Max', 'orgASA_HMax',
             'orgASA_PMax', 'orgpolarsurfaceareaMax', 'orghbdamsaccMax', 'orghbdamsdonMax', 'orgavgpolMin',
             'orgrefractivityMin', 'orgmaximalprojectionareaMin', 'orgmaximalprojectionradiusMin',
             'orgmaximalprojectionsizeMin', 'orgminimalprojectionareaMin', 'orgminimalprojectionradiusMin',
             'orgminimalprojectionsizeMin', 'orgavgpol_pHdependentMin', 'orgmolpolMin', 'orgvanderwaalsMin',
             'orgASAMin', 'orgASA+Min', 'orgASA-Min', 'orgASA_HMin', 'orgASA_PMin', 'orgpolarsurfaceareaMin',
             'orghbdamsaccMin', 'orghbdamsdonMin', 'orgavgpolArithAvg', 'orgrefractivityArithAvg',
             'orgmaximalprojectionareaArithAvg', 'orgmaximalprojectionradiusArithAvg',
             'orgmaximalprojectionsizeArithAvg', 'orgminimalprojectionareaArithAvg',
             'orgminimalprojectionradiusArithAvg', 'orgminimalprojectionsizeArithAvg',
             'orgavgpol_pHdependentArithAvg', 'orgmolpolArithAvg', 'orgvanderwaalsArithAvg',
             'orgASAArithAvg', 'orgASA+ArithAvg', 'orgASA-ArithAvg', 'orgASA_HArithAvg',
             'orgASA_PArithAvg', 'orgpolarsurfaceareaArithAvg', 'orghbdamsaccArithAvg',
             'orghbdamsdonArithAvg', 'orgavgpolGeomAvg', 'orgrefractivityGeomAvg',
             'orgmaximalprojectionareaGeomAvg', 'orgmaximalprojectionradiusGeomAvg',
             'orgmaximalprojectionsizeGeomAvg', 'orgminimalprojectionareaGeomAvg',
             'orgminimalprojectionradiusGeomAvg', 'orgminimalprojectionsizeGeomAvg',
             'orgavgpol_pHdependentGeomAvg', 'orgmolpolGeomAvg', 'orgvanderwaalsGeomAvg', 'orgASAGeomAvg',
             'orgASA+GeomAvg', 'orgASA-GeomAvg', 'orgASA_HGeomAvg', 'orgASA_PGeomAvg', 'orgpolarsurfaceareaGeomAvg',
             'orghbdamsaccGeomAvg', 'orghbdamsdonGeomAvg', 'oxlikeavgpolMax', 'oxlikerefractivityMax',
             'oxlikemaximalprojectionareaMax', 'oxlikemaximalprojectionradiusMax', 'oxlikemaximalprojectionsizeMax',
             'oxlikeminimalprojectionareaMax', 'oxlikeminimalprojectionradiusMax', 'oxlikeminimalprojectionsizeMax',
             'oxlikeavgpol_pHdependentMax', 'oxlikemolpolMax', 'oxlikevanderwaalsMax', 'oxlikeASAMax', 'oxlikeASA+Max',
             'oxlikeASA-Max', 'oxlikeASA_HMax', 'oxlikeASA_PMax', 'oxlikepolarsurfaceareaMax', 'oxlikehbdamsaccMax',
             'oxlikehbdamsdonMax', 'oxlikeavgpolMin', 'oxlikerefractivityMin', 'oxlikemaximalprojectionareaMin',
             'oxlikemaximalprojectionradiusMin', 'oxlikemaximalprojectionsizeMin', 'oxlikeminimalprojectionareaMin',
             'oxlikeminimalprojectionradiusMin', 'oxlikeminimalprojectionsizeMin', 'oxlikeavgpol_pHdependentMin',
             'oxlikemolpolMin', 'oxlikevanderwaalsMin', 'oxlikeASAMin', 'oxlikeASA+Min', 'oxlikeASA-Min',
             'oxlikeASA_HMin', 'oxlikeASA_PMin', 'oxlikepolarsurfaceareaMin', 'oxlikehbdamsaccMin',
             'oxlikehbdamsdonMin', 'oxlikeavgpolArithAvg', 'oxlikerefractivityArithAvg',
             'oxlikemaximalprojectionareaArithAvg', 'oxlikemaximalprojectionradiusArithAvg',
             'oxlikemaximalprojectionsizeArithAvg', 'oxlikeminimalprojectionareaArithAvg',
             'oxlikeminimalprojectionradiusArithAvg', 'oxlikeminimalprojectionsizeArithAvg',
             'oxlikeavgpol_pHdependentArithAvg', 'oxlikemolpolArithAvg', 'oxlikevanderwaalsArithAvg',
             'oxlikeASAArithAvg', 'oxlikeASA+ArithAvg', 'oxlikeASA-ArithAvg', 'oxlikeASA_HArithAvg',
             'oxlikeASA_PArithAvg', 'oxlikepolarsurfaceareaArithAvg', 'oxlikehbdamsaccArithAvg',
             'oxlikehbdamsdonArithAvg', 'oxlikeavgpolGeomAvg', 'oxlikerefractivityGeomAvg',
             'oxlikemaximalprojectionareaGeomAvg', 'oxlikemaximalprojectionradiusGeomAvg',
             'oxlikemaximalprojectionsizeGeomAvg', 'oxlikeminimalprojectionareaGeomAvg',
             'oxlikeminimalprojectionradiusGeomAvg', 'oxlikeminimalprojectionsizeGeomAvg',
             'oxlikeavgpol_pHdependentGeomAvg', 'oxlikemolpolGeomAvg', 'oxlikevanderwaalsGeomAvg', 'oxlikeASAGeomAvg',
             'oxlikeASA+GeomAvg', 'oxlikeASA-GeomAvg', 'oxlikeASA_HGeomAvg', 'oxlikeASA_PGeomAvg',
             'oxlikepolarsurfaceareaGeomAvg', 'oxlikehbdamsaccGeomAvg', 'oxlikehbdamsdonGeomAvg',
             'inorg-water-moleratio', 'org-water-moleratio', 'orgacc-waterdonratio', 'orgdon-wateraccratio',
             'inorg-org-moleratio', 'notwater-water-moleratio', 'Na', 'Li', 'Te', 'Br', 'K', 'C', 'F', 'I', 'Mo', 'O',
             'N', 'P', 'S', 'V', 'Se', 'Zn', 'Co', 'Cl', 'Ga', 'Cs', 'Cr', 'Cu', 'Actinide', 'AlkaliMetal',
             'Lanthanide', 'P1', 'P2', 'P3', 'P4', 'P5', 'P6', 'P7', 'G1', 'G2', 'G3', 'G4', 'G5', 'G6', 'G7', 'G8',
             'G9', 'G10', 'G11', 'G12', 'G13', 'G14', 'G15', 'G16', 'G17', 'G18', 'V0', 'V1', 'V2', 'V3', 'V4', 'V5',
             'V6', 'V7', 'IonizationMax', 'EAMax', 'PaulingElectronegMax', 'PearsonElectronegMax', 'hardnessMax',
             'AtomicRadiusMax', 'IonizationMin', 'EAMin', 'PaulingElectronegMin', 'PearsonElectronegMin', 'hardnessMin',
             'AtomicRadiusMin', 'IonizationMean', 'EAMean', 'PaulingElectronegMean', 'PearsonElectronegMean',
             'hardnessMean', 'AtomicRadiusMean', 'IonizationGeom', 'EAGeom', 'PaulingElectronegGeom',
             'PearsonElectronegGeom', 'hardnessGeom', 'AtomicRadiusGeom', 'IonizationMaxWeighted', 'EAMaxWeighted',
             'PaulingElectronegMaxWeighted', 'PearsonElectronegMaxWeighted', 'hardnessMaxWeighted',
             'AtomicRadiusMaxWeighted', 'IonizationMinWeighted', 'EAMinWeighted', 'PaulingElectronegMinWeighted',
             'PearsonElectronegMinWeighted', 'hardnessMinWeighted', 'AtomicRadiusMinWeighted',
             'IonizationMeanWeighted', 'EAMeanWeighted', 'PaulingElectronegMeanWeighted',
             'PearsonElectronegMeanWeighted', 'hardnessMeanWeighted', 'AtomicRadiusMeanWeighted',
             'IonizationGeomWeighted', 'EAGeomWeighted', 'PaulingElectronegGeomWeighted',
             'PearsonElectronegGeomWeighted', 'hardnessGeomWeighted', 'AtomicRadiusGeomWeighted', 'purity'],
            ['温度', '反应时间', '缓慢冷却', 'pH', '产物泄露', '无机组分数', '有机组分数', 'numberOxlike',
             '组分数', 'orgavgpolMax', 'orgrefractivityMax', 'orgmaximalprojectionareaMax',
             'orgmaximalprojectionradiusMax', 'orgmaximalprojectionsizeMax', 'orgminimalprojectionareaMax',
             'orgminimalprojectionradiusMax', 'orgminimalprojectionsizeMax', 'orgavgpol_pHdependentMax',
             'orgmolpolMax', 'orgvanderwaalsMax', 'orgASAMax', 'orgASA+Max', 'orgASA-Max', 'orgASA_HMax',
             'orgASA_PMax', 'orgpolarsurfaceareaMax', 'orghbdamsaccMax', 'orghbdamsdonMax', 'orgavgpolMin',
             'orgrefractivityMin', 'orgmaximalprojectionareaMin', 'orgmaximalprojectionradiusMin',
             'orgmaximalprojectionsizeMin', 'orgminimalprojectionareaMin', 'orgminimalprojectionradiusMin',
             'orgminimalprojectionsizeMin', 'orgavgpol_pHdependentMin', 'orgmolpolMin', 'orgvanderwaalsMin',
             'orgASAMin', 'orgASA+Min', 'orgASA-Min', 'orgASA_HMin', 'orgASA_PMin', 'orgpolarsurfaceareaMin',
             'orghbdamsaccMin', 'orghbdamsdonMin', 'orgavgpol算术平均', 'orgrefractivity算术平均',
             'orgmaximalprojectionarea算术平均', 'orgmaximalprojectionradius算术平均',
             'orgmaximalprojectionsize算术平均', 'orgminimalprojectionarea算术平均',
             'orgminimalprojectionradius算术平均', 'orgminimalprojectionsize算术平均',
             'orgavgpol_pHdependent算术平均', 'orgmolpol算术平均', 'orgvanderwaals算术平均',
             'orgASA算术平均', 'orgASA+算术平均', 'orgASA-算术平均', 'orgASA_H算术平均',
             'orgASA_P算术平均', 'orgpolarsurfacearea算术平均', 'orghbdamsacc算术平均',
             'orghbdamsdon算术平均', 'orgavgpol几何平均', 'orgrefractivity几何平均',
             'orgmaximalprojectionarea几何平均', 'orgmaximalprojectionradius几何平均',
             'orgmaximalprojectionsize几何平均', 'orgminimalprojectionarea几何平均',
             'orgminimalprojectionradius几何平均', 'orgminimalprojectionsize几何平均',
             'orgavgpol_pHdependent几何平均', 'orgmolpol几何平均', 'orgvanderwaals几何平均', 'orgASA几何平均',
             'orgASA+几何平均', 'orgASA-几何平均', 'orgASA_H几何平均', 'orgASA_P几何平均', 'orgpolarsurfacearea几何平均',
             'orghbdamsacc几何平均', 'orghbdamsdon几何平均', 'oxlikeavgpolMax', 'oxlikerefractivityMax',
             'oxlikemaximalprojectionareaMax', 'oxlikemaximalprojectionradiusMax', 'oxlikemaximalprojectionsizeMax',
             'oxlikeminimalprojectionareaMax', 'oxlikeminimalprojectionradiusMax', 'oxlikeminimalprojectionsizeMax',
             'oxlikeavgpol_pHdependentMax', 'oxlikemolpolMax', 'oxlikevanderwaalsMax', 'oxlikeASAMax', 'oxlikeASA+Max',
             'oxlikeASA-Max', 'oxlikeASA_HMax', 'oxlikeASA_PMax', 'oxlikepolarsurfaceareaMax', 'oxlikehbdamsaccMax',
             'oxlikehbdamsdonMax', 'oxlikeavgpolMin', 'oxlikerefractivityMin', 'oxlikemaximalprojectionareaMin',
             'oxlikemaximalprojectionradiusMin', 'oxlikemaximalprojectionsizeMin', 'oxlikeminimalprojectionareaMin',
             'oxlikeminimalprojectionradiusMin', 'oxlikeminimalprojectionsizeMin', 'oxlikeavgpol_pHdependentMin',
             'oxlikemolpolMin', 'oxlikevanderwaalsMin', 'oxlikeASAMin', 'oxlikeASA+Min', 'oxlikeASA-Min',
             'oxlikeASA_HMin', 'oxlikeASA_PMin', 'oxlikepolarsurfaceareaMin', 'oxlikehbdamsaccMin',
             'oxlikehbdamsdonMin', 'oxlikeavgpol算术平均', 'oxlikerefractivity算术平均',
             'oxlikemaximalprojectionarea算术平均', 'oxlikemaximalprojectionradius算术平均',
             'oxlikemaximalprojectionsize算术平均', 'oxlikeminimalprojectionarea算术平均',
             'oxlikeminimalprojectionradius算术平均', 'oxlikeminimalprojectionsize算术平均',
             'oxlikeavgpol_pHdependent算术平均', 'oxlikemolpol算术平均', 'oxlikevanderwaals算术平均',
             'oxlikeASA算术平均', 'oxlikeASA+算术平均', 'oxlikeASA-算术平均', 'oxlikeASA_H算术平均',
             'oxlikeASA_P算术平均', 'oxlikepolarsurfacearea算术平均', 'oxlikehbdamsacc算术平均',
             'oxlikehbdamsdon算术平均', 'oxlikeavgpol几何平均', 'oxlikerefractivity几何平均',
             'oxlikemaximalprojectionarea几何平均', 'oxlikemaximalprojectionradius几何平均',
             'oxlikemaximalprojectionsize几何平均', 'oxlikeminimalprojectionarea几何平均',
             'oxlikeminimalprojectionradius几何平均', 'oxlikeminimalprojectionsize几何平均',
             'oxlikeavgpol_pHdependent几何平均', 'oxlikemolpol几何平均', 'oxlikevanderwaals几何平均', 'oxlikeASA几何平均',
             'oxlikeASA+几何平均', 'oxlikeASA-几何平均', 'oxlikeASA_H几何平均', 'oxlikeASA_P几何平均',
             'oxlikepolarsurfacearea几何平均', 'oxlikehbdamsacc几何平均', 'oxlikehbdamsdon几何平均',
             'inorg-water-moleratio', 'org-water-moleratio', 'orgacc-waterdonratio', 'orgdon-wateraccratio',
             'inorg-org-moleratio', 'notwater-water-moleratio', 'Na', 'Li', 'Te', 'Br', 'K', 'C', 'F', 'I', 'Mo', 'O',
             'N', 'P', 'S', 'V', 'Se', 'Zn', 'Co', 'Cl', 'Ga', 'Cs', 'Cr', 'Cu', 'Actinide', 'AlkaliMetal',
             '镧系元素', 'P1', 'P2', 'P3', 'P4', 'P5', 'P6', 'P7', 'G1', 'G2', 'G3', 'G4', 'G5', 'G6', 'G7', 'G8',
             'G9', 'G10', 'G11', 'G12', 'G13', 'G14', 'G15', 'G16', 'G17', 'G18', 'V0', 'V1', 'V2', 'V3', 'V4', 'V5',
             'V6', 'V7', '最大电离能', '最大电子亲和能', 'Pauling电负性Max', 'Pearson电负性Max', '硬度Max',
             '原子半径Max', '电离能Min', '电子亲和能Min', 'Pauling电负性Min', 'Pearson电负性Min', '硬度Min',
             '原子半径Min', '电离能Mean', '电子亲和能Mean', 'Pauling电负性Mean', 'Pearson电负性Mean',
             '硬度Mean', '原子半径Mean', '电离能Geom', 'EAGeom', 'Pauling电负性Geom',
             'Pearson电负性Geom', '硬度Geom', '原子半径Geom', '电离能MaxWeighted', '电子亲和能MaxWeighted',
             'Pauling电负性MaxWeighted', 'Pearson电负性MaxWeighted', '硬度MaxWeighted',
             '原子半径MaxWeighted', '电离能MinWeighted', 'EAMinWeighted', 'Pauling电负性MinWeighted',
             'Pearson电负性MinWeighted', '硬度MinWeighted', '原子半径MinWeighted',
             '电离能MeanWeighted', '电子亲和能MeanWeighted', 'Pauling电负性MeanWeighted',
             'Pearson电负性MeanWeighted', '硬度MeanWeighted', '原子半径MeanWeighted',
             '电离能GeomWeighted', '电子亲和能GeomWeighted', 'Pauling电负性GeomWeighted',
             'Pearson电负性GeomWeighted', '硬度GeomWeighted', '原子半径GeomWeighted', '纯度']]

test_key = [['time', 'slowCool', 'pH', 'leak', 'numberInorg', 'numberOrg',
            'numberOxlike', 'numberComponents', 'orgavgpolMax',
            'orgrefractivityMax', 'orgmaximalprojectionareaMax',
            'orgmaximalprojectionradiusMax', 'orgmaximalprojectionsizeMax',
            'orgminimalprojectionareaMax', 'orgminimalprojectionradiusMax',
            'orgminimalprojectionsizeMax', 'orgavgpol_pHdependentMax',
            'orgmolpolMax', 'orgvanderwaalsMax', 'orgASAMax', 'orgASA+Max',
            'orgASA-Max', 'orgASA_HMax', 'orgASA_PMax', 'orgpolarsurfaceareaMax',
            'orghbdamsaccMax', 'orghbdamsdonMax', 'orgavgpolMin', 'orgrefractivityMin',
            'orgmaximalprojectionareaMin', 'orgmaximalprojectionradiusMin',
            'orgmaximalprojectionsizeMin', 'orgminimalprojectionareaMin'],
            ['反应时间', '慢速冷却', 'pH', '产物泄露', '无机组分数', '有机组分数量',
             'Ox类似物数量', '组分数', '有机物平均分子极化率Max',
            '有机物最大折射率', '有机物maximalprojectionareaMax',
            '有机物maximalprojectionradiusMax', '有机物maximalprojectionsizeMax',
            '有机物minimalprojectionareaMax', '有机物minimalprojectionradiusMax',
            '有机物minimalprojectionsizeMax', '有机物平均分子极化率-pH依赖关系Max',
            '有机物最大分子极性', '有机物最大范德华立体表面积', '有机分子最大亲水表面积', '有机物最大亲水表面积+',
            '有机物最大亲水表面积', '有机物最大亲水表面积_H', '有机物最大亲水表面积_P', '有机物最大极性表面积',
            '有机物最大氢键受体数量', '有机物最大氢键给体数', '有机物平均分子极化率Min', '有机物最小折射率',
            '有机物maximalprojectionareaMin', '有机物maximalprojectionradiusMin',
            '有机物maximalprojectionsizeMin', '有机物minimalprojectionareaMin'
             ]
            ]
feat_first = [['orgvanderwaalsMin', 'orgASA+Min', 'orghbdamsdonGeomAvg',
              'PaulingElectronegMean', 'hardnessMaxWeighted', 'AtomicRadiusMeanWeighted'],
              ['orgMin', '有机物最小亲水表面积+', '有机物氢键给体几何平均值',
               '平均Pauling电负性', '最大质量的硬度', '重均原子半径']
              ]

feat_top6 = [['time', 'hardnessMinWeighted', 'orgASA_HGeomAvg', 'leak',
             'inorg-water-moleratio', 'orgvanderwaalsArithAvg'],
             ['反应时间', '最低质量的硬度', '有机物亲水表面积_H几何平均', '产物泄露',
             '无机组分/水摩尔比', '有机物范德华立体表面积算术平均']
             ]

feat_top9 = [['time', 'hardnessMinWeighted', 'orgASA_HGeomAvg', 'leak',
             'inorg-water-moleratio', 'orgvanderwaalsArithAvg',
             'orghbdamsaccMax', 'temp', 'EAMinWeighted'],
             ['反应时间', '最低质量的硬度', '有机物亲水表面积_H几何平均', '产物泄露',
             '无机组分/水摩尔比', '有机物范德华立体表面积算术平均',
             '有机物最大氢键受体数量', '反应温度', '最低质量的电子亲和能']
             ]